import {
  BookingSummary,
  DailyEssentialProblem,
  MessageSummary,
  ProviderSummary,
  ServiceCategory,
  ServiceSummary,
} from "@/types/marketplace";

export const sampleCategories: ServiceCategory[] = [
  { id: "c1", name: "Home Services", slug: "home-services" },
  { id: "c2", name: "Plumber", slug: "plumber", parentSlug: "home-services" },
  { id: "c3", name: "Electrician", slug: "electrician", parentSlug: "home-services" },
  { id: "c4", name: "IT Services", slug: "it-services" },
  { id: "c5", name: "Repair Services", slug: "repair-services" },
  { id: "c6", name: "Education", slug: "education" },
  { id: "c11", name: "Home Tutor", slug: "home-tutor", parentSlug: "education" },
  { id: "c7", name: "Health", slug: "health" },
  { id: "c8", name: "Beauty & Salon", slug: "beauty-salon" },
  { id: "c9", name: "Transport", slug: "transport" },
  { id: "c12", name: "Car Parking", slug: "car-parking", parentSlug: "transport" },
  { id: "c10", name: "Events", slug: "events" },
  { id: "c13", name: "Part Time Jobs", slug: "part-time-jobs" },
  { id: "c14", name: "Short-Term Services", slug: "short-term-services" },
  { id: "c15", name: "Short-Term Rent", slug: "short-term-rent", parentSlug: "short-term-services" },
  { id: "c16", name: "Short-Term Investment", slug: "short-term-investment", parentSlug: "short-term-services" },
];

export const sampleProviders: ProviderSummary[] = [
  {
    id: "p1",
    name: "Rahim Electric Care",
    title: "Certified Home Electrician",
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    rating: 4.8,
    reviewCount: 182,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p2",
    name: "CoolFix AC Team",
    title: "AC Repair & Maintenance",
    division: "Dhaka",
    district: "Dhaka",
    area: "Uttara",
    rating: 4.7,
    reviewCount: 136,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p3",
    name: "Shiksha Tutors BD",
    title: "Home & Online Tutors",
    division: "Chattogram",
    district: "Chattogram",
    area: "Panchlaish",
    rating: 4.9,
    reviewCount: 214,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p4",
    name: "City Parking Assist",
    title: "Daily and Monthly Car Parking Solutions",
    division: "Dhaka",
    district: "Dhaka",
    area: "Dhanmondi",
    rating: 4.5,
    reviewCount: 94,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p5",
    name: "QuickShift Jobs BD",
    title: "Part-Time and Shift-Based Job Matching",
    division: "Dhaka",
    district: "Gazipur",
    area: "Tongi",
    rating: 4.6,
    reviewCount: 121,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p6",
    name: "ShortStay Capital Network",
    title: "Short-Term Rent and Small Investment Support",
    division: "Chattogram",
    district: "Chattogram",
    area: "Agrabad",
    rating: 4.4,
    reviewCount: 76,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p7",
    name: "PipeCare 24/7",
    title: "Emergency Plumbing and Sanitary Works",
    division: "Khulna",
    district: "Khulna",
    area: "Sonadanga",
    rating: 4.6,
    reviewCount: 108,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p8",
    name: "Prime Home Medics",
    title: "In-Home Nursing and Caregiver Service",
    division: "Dhaka",
    district: "Dhaka",
    area: "Bashundhara",
    rating: 4.7,
    reviewCount: 143,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p9",
    name: "Glamour Doorstep Salon",
    title: "At-Home Beauty and Grooming Experts",
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulshan",
    rating: 4.8,
    reviewCount: 201,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p10",
    name: "CloudOffice IT Support",
    title: "SME IT Maintenance and Remote Support",
    division: "Dhaka",
    district: "Dhaka",
    area: "Motijheel",
    rating: 4.5,
    reviewCount: 88,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p11",
    name: "EventHive Bangladesh",
    title: "Event Planning, Decor, and Logistics",
    division: "Chattogram",
    district: "Chattogram",
    area: "Nasirabad",
    rating: 4.6,
    reviewCount: 119,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "p12",
    name: "MoveNow Transport BD",
    title: "City Shifting and Mini-Transport Support",
    division: "Rajshahi",
    district: "Rajshahi",
    area: "Boalia",
    rating: 4.4,
    reviewCount: 67,
    approved: true,
    image:
      "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=600&q=80",
  },
];

export const sampleServices: ServiceSummary[] = [
  {
    id: "s1",
    title: "AC Not Cooling Diagnosis & Repair",
    slug: "ac-not-cooling-diagnosis-repair",
    description: "Quick inspection, gas refill recommendation, and cooling restoration.",
    categorySlug: "repair-services",
    providerId: "p2",
    priceFrom: 800,
    priceTo: 2500,
    division: "Dhaka",
    district: "Dhaka",
    area: "Uttara",
    latitude: 23.8759,
    longitude: 90.3795,
    supportedProblemSizes: ["SMALL", "MEDIUM", "BIG"],
    tags: ["ac", "cooling", "repair"],
    image:
      "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s2",
    title: "Home Electric Line Fixing",
    slug: "home-electric-line-fixing",
    description: "Short circuit detection, wiring fixes, and safety checks.",
    categorySlug: "electrician",
    providerId: "p1",
    priceFrom: 500,
    priceTo: 2200,
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    latitude: 23.8223,
    longitude: 90.3654,
    supportedProblemSizes: ["SMALL", "MEDIUM"],
    tags: ["electric", "wiring", "home"],
    image:
      "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s3",
    title: "Class 9-12 Science Tutor",
    slug: "class-9-12-science-tutor",
    description: "Experienced tutor for Math, Physics, and Chemistry in Bangla/English medium.",
    categorySlug: "education",
    providerId: "p3",
    priceFrom: 3500,
    priceTo: 9000,
    division: "Chattogram",
    district: "Chattogram",
    area: "Panchlaish",
    latitude: 22.3569,
    longitude: 91.8252,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["tutor", "science", "education"],
    image:
      "https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s4",
    title: "Home Tutor for Class 6-10 (Bangla + English)",
    slug: "home-tutor-class-6-10",
    description: "Reliable home tutoring support for school students with weekly progress tracking.",
    categorySlug: "home-tutor",
    providerId: "p3",
    priceFrom: 2500,
    priceTo: 7000,
    division: "Dhaka",
    district: "Dhaka",
    area: "Dhanmondi",
    latitude: 23.746,
    longitude: 90.376,
    supportedProblemSizes: ["SMALL", "MEDIUM", "BIG"],
    tags: ["home tutor", "tuition", "school", "coaching"],
    image:
      "https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s5",
    title: "Secure Car Parking (Daily/Monthly)",
    slug: "secure-car-parking-daily-monthly",
    description: "Find verified parking spaces near offices, hospitals, and residential blocks.",
    categorySlug: "car-parking",
    providerId: "p4",
    priceFrom: 150,
    priceTo: 4500,
    division: "Dhaka",
    district: "Dhaka",
    area: "Dhanmondi",
    latitude: 23.7465,
    longitude: 90.3771,
    supportedProblemSizes: ["SMALL", "MEDIUM"],
    tags: ["car parking", "parking", "garage", "daily parking"],
    image:
      "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s6",
    title: "Part-Time Job Matching for Students",
    slug: "part-time-job-matching-students",
    description: "Match students and job seekers with verified flexible shift-based opportunities.",
    categorySlug: "part-time-jobs",
    providerId: "p5",
    priceFrom: 300,
    priceTo: 2000,
    division: "Dhaka",
    district: "Gazipur",
    area: "Tongi",
    latitude: 23.8917,
    longitude: 90.4023,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["part time", "job", "shift", "student job"],
    image:
      "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s7",
    title: "Short-Term Rent Setup (1-6 Months)",
    slug: "short-term-rent-setup",
    description: "Assistance for finding short-stay room, bachelor flat, or temporary office rent.",
    categorySlug: "short-term-rent",
    providerId: "p6",
    priceFrom: 1000,
    priceTo: 6500,
    division: "Chattogram",
    district: "Chattogram",
    area: "Agrabad",
    latitude: 22.3285,
    longitude: 91.811,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["short term rent", "temporary rent", "flat rent", "office rent"],
    image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s8",
    title: "Short-Term Small Investment Advisory",
    slug: "short-term-small-investment-advisory",
    description: "Get guidance for low-risk short-term investment plans tailored to local users.",
    categorySlug: "short-term-investment",
    providerId: "p6",
    priceFrom: 1200,
    priceTo: 8000,
    division: "Dhaka",
    district: "Dhaka",
    area: "Uttara",
    latitude: 23.874,
    longitude: 90.398,
    supportedProblemSizes: ["BIG"],
    tags: ["short term investment", "investment", "low risk", "finance"],
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s9",
    title: "Emergency Pipe Leak Fix (Within 90 Minutes)",
    slug: "emergency-pipe-leak-fix",
    description: "Rapid-response plumbing support for kitchen, bathroom, and rooftop pipelines.",
    categorySlug: "plumber",
    providerId: "p7",
    priceFrom: 700,
    priceTo: 2800,
    division: "Khulna",
    district: "Khulna",
    area: "Sonadanga",
    latitude: 22.8456,
    longitude: 89.5403,
    supportedProblemSizes: ["SMALL", "MEDIUM", "BIG"],
    tags: ["plumber", "leak", "pipeline", "emergency"],
    image:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s10",
    title: "In-Home Nurse (12 Hour Shift)",
    slug: "in-home-nurse-12-hour-shift",
    description: "Day and night nursing support for post-surgery and elderly patients.",
    categorySlug: "health",
    providerId: "p8",
    priceFrom: 1800,
    priceTo: 4500,
    division: "Dhaka",
    district: "Dhaka",
    area: "Bashundhara",
    latitude: 23.8146,
    longitude: 90.4259,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["nurse", "caregiver", "healthcare", "home care"],
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s11",
    title: "Doorstep Bridal & Party Makeup",
    slug: "doorstep-bridal-party-makeup",
    description: "Certified beauty artists for bridal, engagement, and party makeover packages.",
    categorySlug: "beauty-salon",
    providerId: "p9",
    priceFrom: 2500,
    priceTo: 15000,
    division: "Dhaka",
    district: "Dhaka",
    area: "Gulshan",
    latitude: 23.7925,
    longitude: 90.4078,
    supportedProblemSizes: ["SMALL", "MEDIUM", "BIG"],
    tags: ["salon", "bridal", "makeup", "beauty"],
    image:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s12",
    title: "Office IT AMC Support (Monthly)",
    slug: "office-it-amc-support-monthly",
    description: "Managed IT support for startups and SMEs: network, printers, and endpoint issues.",
    categorySlug: "it-services",
    providerId: "p10",
    priceFrom: 5000,
    priceTo: 28000,
    division: "Dhaka",
    district: "Dhaka",
    area: "Motijheel",
    latitude: 23.7321,
    longitude: 90.4174,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["it", "office", "network", "amc"],
    image:
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s13",
    title: "Wedding Event Planning Full Stack",
    slug: "wedding-event-planning-full-stack",
    description: "End-to-end event planning with decor, catering, logistics, and photography vendors.",
    categorySlug: "events",
    providerId: "p11",
    priceFrom: 45000,
    priceTo: 350000,
    division: "Chattogram",
    district: "Chattogram",
    area: "Nasirabad",
    latitude: 22.366,
    longitude: 91.806,
    supportedProblemSizes: ["BIG"],
    tags: ["event", "wedding", "decor", "catering"],
    image:
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s14",
    title: "Mini Truck for Home Shifting (City)",
    slug: "mini-truck-home-shifting-city",
    description: "Affordable same-day mini truck and loading support for household moving.",
    categorySlug: "transport",
    providerId: "p12",
    priceFrom: 2200,
    priceTo: 10000,
    division: "Rajshahi",
    district: "Rajshahi",
    area: "Boalia",
    latitude: 24.3745,
    longitude: 88.6042,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["transport", "truck", "shifting", "moving"],
    image:
      "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s15",
    title: "Monthly Family Medical Attendant",
    slug: "monthly-family-medical-attendant",
    description: "Dedicated home medical attendant with medicine schedule and vitals support.",
    categorySlug: "health",
    providerId: "p8",
    priceFrom: 12000,
    priceTo: 38000,
    division: "Dhaka",
    district: "Dhaka",
    area: "Banani",
    latitude: 23.7937,
    longitude: 90.4066,
    supportedProblemSizes: ["BIG"],
    tags: ["health", "attendant", "elderly care", "medical"],
    image:
      "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s16",
    title: "SSC Crash Course Home Tutor",
    slug: "ssc-crash-course-home-tutor",
    description: "90-day intensive SSC preparation with weekly mock tests and progress reports.",
    categorySlug: "home-tutor",
    providerId: "p3",
    priceFrom: 4500,
    priceTo: 12000,
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    latitude: 23.8103,
    longitude: 90.4125,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["ssc", "tutor", "crash course", "education"],
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s17",
    title: "Corporate Car Parking Management",
    slug: "corporate-car-parking-management",
    description: "Parking allocation and pass management for office teams and commercial buildings.",
    categorySlug: "car-parking",
    providerId: "p4",
    priceFrom: 5000,
    priceTo: 30000,
    division: "Dhaka",
    district: "Dhaka",
    area: "Motijheel",
    latitude: 23.7312,
    longitude: 90.4177,
    supportedProblemSizes: ["MEDIUM", "BIG"],
    tags: ["parking", "corporate", "vehicle", "management"],
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "s18",
    title: "Weekend Part-Time Job Bundle",
    slug: "weekend-part-time-job-bundle",
    description: "Curated weekend and evening opportunities with document and profile assistance.",
    categorySlug: "part-time-jobs",
    providerId: "p5",
    priceFrom: 500,
    priceTo: 2500,
    division: "Dhaka",
    district: "Dhaka",
    area: "Mirpur",
    latitude: 23.8041,
    longitude: 90.3667,
    supportedProblemSizes: ["SMALL", "MEDIUM", "BIG"],
    tags: ["part-time", "weekend", "job", "career"],
    image:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80",
  },
];

export const sampleBookings: BookingSummary[] = [
  {
    id: "b1",
    serviceId: "s1",
    customerName: "Nafisa",
    providerName: "CoolFix AC Team",
    scheduledAt: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    status: "PENDING",
    problemText: "My AC is not cooling",
  },
  {
    id: "b2",
    serviceId: "s2",
    customerName: "Arif",
    providerName: "Rahim Electric Care",
    scheduledAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    status: "COMPLETED",
    problemText: "Switchboard sparks when I turn on fan",
  },
  {
    id: "b3",
    serviceId: "s9",
    customerName: "Tanvir",
    providerName: "PipeCare 24/7",
    scheduledAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    status: "ACCEPTED",
    problemText: "Bathroom pipe burst and water leaking rapidly",
  },
  {
    id: "b4",
    serviceId: "s10",
    customerName: "Sadia",
    providerName: "Prime Home Medics",
    scheduledAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
    status: "PENDING",
    problemText: "Need nurse support for post-surgery patient",
  },
  {
    id: "b5",
    serviceId: "s11",
    customerName: "Maliha",
    providerName: "Glamour Doorstep Salon",
    scheduledAt: new Date(Date.now() + 6 * 24 * 3600 * 1000).toISOString(),
    status: "ACCEPTED",
    problemText: "Need bridal and family makeup package at home",
  },
  {
    id: "b6",
    serviceId: "s13",
    customerName: "Rafi",
    providerName: "EventHive Bangladesh",
    scheduledAt: new Date(Date.now() + 18 * 24 * 3600 * 1000).toISOString(),
    status: "PENDING",
    problemText: "Complete wedding event coordination for 600 guests",
  },
  {
    id: "b7",
    serviceId: "s14",
    customerName: "Jannat",
    providerName: "MoveNow Transport BD",
    scheduledAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    status: "COMPLETED",
    problemText: "Need mini truck for apartment shifting",
  },
  {
    id: "b8",
    serviceId: "s16",
    customerName: "Nafisa",
    providerName: "Shiksha Tutors BD",
    scheduledAt: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
    status: "PENDING",
    problemText: "Looking for SSC crash course tutor from next week",
  },
  {
    id: "b9",
    serviceId: "s18",
    customerName: "Arif",
    providerName: "QuickShift Jobs BD",
    scheduledAt: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    status: "COMPLETED",
    problemText: "Need weekend part-time opportunities near Mirpur",
  },
  {
    id: "b10",
    serviceId: "s17",
    customerName: "Tahmid",
    providerName: "City Parking Assist",
    scheduledAt: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
    status: "ACCEPTED",
    problemText: "Need monthly office parking slots for team cars",
  },
];

export const sampleMessages: MessageSummary[] = [
  {
    id: "m1",
    bookingId: "b1",
    from: "Nafisa",
    to: "CoolFix AC Team",
    content: "Can you come after 4pm?",
    createdAt: new Date().toISOString(),
  },
  {
    id: "m2",
    bookingId: "b1",
    from: "CoolFix AC Team",
    to: "Nafisa",
    content: "Yes, our technician will arrive between 4:30-5pm.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "m3",
    bookingId: "b3",
    from: "PipeCare 24/7",
    to: "Tanvir",
    content: "Our plumber is on the way. Please keep the main valve off.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "m4",
    bookingId: "b4",
    from: "Sadia",
    to: "Prime Home Medics",
    content: "Can you provide female nurse availability for night shift?",
    createdAt: new Date().toISOString(),
  },
  {
    id: "m5",
    bookingId: "b5",
    from: "Glamour Doorstep Salon",
    to: "Maliha",
    content: "Please share your event timeline so we can assign two artists.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "m6",
    bookingId: "b8",
    from: "Nafisa",
    to: "Shiksha Tutors BD",
    content: "Need classes 4 days a week after 6:30pm.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "m7",
    bookingId: "b9",
    from: "QuickShift Jobs BD",
    to: "Arif",
    content: "We matched you with two evening shift retail roles in Mirpur.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "m8",
    bookingId: "b10",
    from: "Tahmid",
    to: "City Parking Assist",
    content: "Need 8 spots from next Monday near Motijheel office area.",
    createdAt: new Date().toISOString(),
  },
];

export const dailyEssentialProblems: DailyEssentialProblem[] = [
  {
    id: "dp1",
    title: "Water pipe leakage in kitchen",
    description: "Continuous leak causing water waste and floor damage risk.",
    categorySlug: "plumber",
    problemSize: "SMALL",
    localContext: "Very common in old apartments across Dhaka and Chattogram.",
    commonAreas: ["Mirpur", "Uttara", "Agrabad"],
  },
  {
    id: "dp2",
    title: "Home wiring spark and breaker trip",
    description: "Switch board trips and sparks when multiple devices run.",
    categorySlug: "electrician",
    problemSize: "MEDIUM",
    localContext: "Frequent in older buildings with heavy fan/AC usage during summer.",
    commonAreas: ["Dhanmondi", "Mirpur", "Sonadanga"],
  },
  {
    id: "dp3",
    title: "AC not cooling during heat wave",
    description: "Urgent maintenance needed due to summer temperature spikes.",
    categorySlug: "repair-services",
    problemSize: "MEDIUM",
    localContext: "Peak seasonal demand across major metro districts.",
    commonAreas: ["Uttara", "Panchlaish", "Khalishpur"],
  },
  {
    id: "dp4",
    title: "Urgent in-home nurse support",
    description: "Post-surgery patient needs immediate day-night care.",
    categorySlug: "health",
    problemSize: "BIG",
    localContext: "High priority family need, often arranged within 24 hours.",
    commonAreas: ["Dhaka", "Chattogram", "Khulna"],
  },
  {
    id: "dp5",
    title: "Board exam tutor needed quickly",
    description: "Student requires short-term intensive coaching support.",
    categorySlug: "education",
    problemSize: "MEDIUM",
    localContext: "Common around SSC/HSC exam periods in urban and suburban areas.",
    commonAreas: ["Gazipur", "Mirpur", "Panchlaish"],
  },
  {
    id: "dp6",
    title: "Wedding event full package coordination",
    description: "Venue setup, food, decoration, and photography all-in-one.",
    categorySlug: "events",
    problemSize: "BIG",
    localContext: "Large seasonal spend category in both city and district level.",
    commonAreas: ["Dhaka", "Chattogram", "Cox's Bazar"],
  },
  {
    id: "dp7",
    title: "Need a home tutor from next week",
    description: "Family looking for trusted tutor for school-going child.",
    categorySlug: "home-tutor",
    problemSize: "MEDIUM",
    localContext: "Very frequent urban household request after exam results.",
    commonAreas: ["Mirpur", "Dhanmondi", "Panchlaish"],
  },
  {
    id: "dp8",
    title: "No safe parking near office",
    description: "Daily office commuters need secure, affordable parking slots.",
    categorySlug: "car-parking",
    problemSize: "SMALL",
    localContext: "Common in congested commercial zones and market areas.",
    commonAreas: ["Motijheel", "Dhanmondi", "Agrabad"],
  },
  {
    id: "dp9",
    title: "Looking for part-time evening job",
    description: "Students or homemakers seeking flexible earning opportunities.",
    categorySlug: "part-time-jobs",
    problemSize: "MEDIUM",
    localContext: "High demand among university students and freshers.",
    commonAreas: ["Tongi", "Mirpur", "Khulna"],
  },
  {
    id: "dp10",
    title: "Need short-term rent for 3 months",
    description: "Temporary housing needed for work, treatment, or study transfer.",
    categorySlug: "short-term-rent",
    problemSize: "BIG",
    localContext: "Often needed by district-to-city families and professionals.",
    commonAreas: ["Uttara", "Bashundhara", "Agrabad"],
  },
  {
    id: "dp11",
    title: "Want low-risk short-term investment option",
    description: "Users looking for small capital growth plans within limited period.",
    categorySlug: "short-term-investment",
    problemSize: "BIG",
    localContext: "Growing demand among middle-income and freelancer households.",
    commonAreas: ["Dhaka", "Chattogram", "Khulna"],
  },
  {
    id: "dp12",
    title: "Server and office internet keeps dropping",
    description: "SME office needs urgent network stabilization and IT support SLA.",
    categorySlug: "it-services",
    problemSize: "BIG",
    localContext: "Common in growing startups depending on remote and cloud workflows.",
    commonAreas: ["Motijheel", "Banani", "Agrabad"],
  },
  {
    id: "dp13",
    title: "Need doorstep salon service for event",
    description: "Family requires multi-person makeup and grooming support at home.",
    categorySlug: "beauty-salon",
    problemSize: "MEDIUM",
    localContext: "Very common during wedding and festive seasons.",
    commonAreas: ["Gulshan", "Dhanmondi", "Khulna"],
  },
  {
    id: "dp14",
    title: "Urgent apartment shifting this weekend",
    description: "Need mini-truck, loader, and packing support in one booking.",
    categorySlug: "transport",
    problemSize: "BIG",
    localContext: "Frequent for job relocation and end-of-lease moves.",
    commonAreas: ["Rajshahi", "Mirpur", "Uttara"],
  },
  {
    id: "dp15",
    title: "Need affordable caregiver for elderly parent",
    description: "Family seeks trusted day-care support and medicine reminders.",
    categorySlug: "health",
    problemSize: "BIG",
    localContext: "Growing demand in dual-income urban families.",
    commonAreas: ["Bashundhara", "Banani", "Chattogram"],
  },
  {
    id: "dp16",
    title: "Office building needs managed parking slots",
    description: "Business teams need monthly reserved parking and vehicle tracking.",
    categorySlug: "car-parking",
    problemSize: "MEDIUM",
    localContext: "High demand in dense commercial zones.",
    commonAreas: ["Motijheel", "Gulshan", "Agrabad"],
  },
  {
    id: "dp17",
    title: "Need complete event vendor package quickly",
    description: "Customer wants venue decor, food, and stage setup from one coordinator.",
    categorySlug: "events",
    problemSize: "BIG",
    localContext: "Very common for wedding seasons and corporate annual events.",
    commonAreas: ["Dhaka", "Chattogram", "Sylhet"],
  },
  {
    id: "dp18",
    title: "Need short-term room near hospital",
    description: "Families seek 1-2 month temporary accommodation for treatment visits.",
    categorySlug: "short-term-rent",
    problemSize: "MEDIUM",
    localContext: "Often needed by district families coming to major cities.",
    commonAreas: ["Uttara", "Dhanmondi", "Panchlaish"],
  },
];
